name: state_bloc
description: A new Flutter package.
version: 0.0.2
homepage: https://github.com/ashishrawat2911/state_bloc

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: