name: state_bloc
description: StateBloc helps the Widget tree to rebuild again with the help of streams.
version: 1.0.1
homepage: https://github.com/ashishrawat2911/state_bloc

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: